apiVersion: v1
kind: PersistentVolume
metadata:
  name: scylla-rack-0
  labels:
    app: scylla-rack-0
spec:
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/scylla/rack-0"
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: data-scylla-production-home-rack-0
    namespace: testbed

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: scylla-rack-1
  labels:
    app: scylla-rack-1
spec:
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/scylla/rack-1"
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: data-scylla-production-home-rack-1
    namespace: testbed

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: scylla-rack-2
  labels:
    app: scylla-rack-2
spec:
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/scylla/rack-1"
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    name: data-scylla-production-home-rack-2
    namespace: testbed