apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-config
data:
  scylla.yaml: |
    commitlog_sync_period_in_ms: 1200000
    range_request_timeout_in_ms: 600000
    read_request_timeout_in_ms: 600000 
    write_request_timeout_in_ms: 600000 
    cas_contention_timeout_in_ms: 600000
    request_timeout_in_ms: 1200000
    counter_write_request_timeout_in_ms: 600000
    enable_parallelized_aggregation: false
