apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-config
data:
  scylla.yaml: |
    commitlog_sync_period_in_ms: 120000
    read_request_timeout_in_ms: 60000 
    write_request_timeout_in_ms: 24000 
    cas_contention_timeout_in_ms: 12000
    request_timeout_in_ms: 120000
