scylla-manager:
  image:
    tag: 3.0.2
  fullnameOverride: scylla-manager
  scylla:
    fullnameOverride: scylla-manager
    racks:
      - name: manager-rack
        members: 1
        storage:
          capacity: 100Gi
        resources:
          limits:
            cpu: 1
            memory: 200Mi
          requests:
            cpu: 1
            memory: 200Mi
    scyllaImage:
      tag: 5.1.7
    agentImage:
      tag: 3.0.2
  serviceMonitor:
    create: true